micronaut:
  application:
    name: design_patterns
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
